language: php
php:
  - 7.3

before_script:
  - phpenv config-rm xdebug.ini
  - touch database/database.sqlite
  - composer install --no-interaction
  - npm install

script:
  - npm run production
  - vendor/bin/phpunit
  - vendor/bin/phpcs
